env:
- GO111MODULE=on
builds:
- main: ./cmd/ksort/main.go
  binary: ksort
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: zip
  files:
  - LICENSE.txt
  - README.md
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
krews:
- name: sort-manifests
  homepage: https://github.com/superbrothers/ksort
  description: |
    When installing manifests, they should be sorted in a proper order by Kind.
    For example, Namespace object must be in the first place when installing
    them.

    ksort sorts manifest files in a proper order by Kind, which is implementd by
    using tiller.SortByKind() in Kubernetes Helm.
  short_description: Sort manifest files in a proper order by Kind
  skip_upload: true
