env:
- GO111MODULE=on
- GOPROXY=https://gocenter.io
builds:
- main: ./cmd/ksort/main.go
  binary: ksort
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: zip
  files:
  - LICENSE.txt
  - README.md
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
