apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: sort-manifests
spec:
  version: {{ .TagName }}
  shortDescription: Sort manifest files in a proper order by Kind
  description: |
    When installing manifests, they should be sorted in a proper order by Kind.
    For example, Namespace object must be in the first place when installing
    them.

    ksort sorts manifest files in a proper order by Kind, which is implementd by
    using tiller.SortByKind() in Kubernetes Helm.
  homepage: https://github.com/superbrothers/ksort
  platforms:
  - {{addURIAndSha "https://github.com/superbrothers/ksort/releases/download/{{ .TagName }}/ksort-darwin-amd64.zip" .TagName }}
    bin: ksort
    files:
    - from: "*"
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - {{addURIAndSha "https://github.com/superbrothers/ksort/releases/download/{{ .TagName }}/ksort-linux-amd64.zip" .TagName }}
    bin: ksort
    files:
    - from: "*"
      to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - {{addURIAndSha "https://github.com/superbrothers/ksort/releases/download/{{ .TagName }}/ksort-windows-amd64.zip" .TagName }}
    bin: ksort
    files:
    - from: "*"
      to: .
    selector:
      matchLabels:
        os: windows
        arch: amd64
